In [1]:
import testing

In [2]:
testing.make_tests("data/small", 20, 5, 8)

Test 1: [3, 5, 2, 1, 4, 6]
Test 2: [5, 4, 6, 1, 3, 2]
Test 3: [1, 2, 4, 5, 3, 7, 6]
Test 4: [2, 7, 3, 6, 5, 1, 4]
Test 5: [6, 4, 1, 3, 7, 2, 5]
Test 6: [6, 3, 1, 4, 5, 2]
Test 7: [8, 1, 3, 4, 6, 2, 5, 7]
Test 8: [2, 4, 5, 3, 1]
Test 9: [2, 4, 7, 5, 1, 6, 3]
Test 10: [2, 7, 6, 5, 8, 4, 1, 3]
Test 11: [1, 5, 4, 3, 2]
Test 12: [2, 4, 3, 1, 5, 6, 7]
Test 13: [3, 6, 2, 4, 5, 7, 1]
Test 14: [3, 5, 4, 8, 1, 7, 2, 6]
Test 15: [1, 5, 4, 2, 3]
Test 16: [1, 3, 5, 2, 6, 4, 7]
Test 17: [1, 8, 3, 6, 2, 7, 4, 5]
Test 18: [3, 5, 1, 2, 4]
Test 19: [5, 8, 2, 3, 1, 4, 6, 7]
Test 20: [2, 7, 3, 8, 5, 1, 6, 4]

In [7]:
testing.make_tests("data/medium", 15, 10, 15)

Test 1: [10, 8, 5, 4, 9, 3, 1, 7, 11, 2, 6, 12]
Test 2: [6, 2, 8, 5, 11, 1, 9, 10, 3, 4, 7]
Test 3: [1, 4, 11, 10, 7, 6, 3, 9, 2, 8, 5]
Test 4: [10, 11, 9, 2, 8, 5, 1, 7, 3, 4, 6]
Test 5: [7, 3, 5, 4, 6, 11, 12, 10, 2, 1, 9, 8]
Test 6: [3, 5, 7, 1, 4, 9, 6, 2, 10, 8]
Test 7: [11, 6, 2, 12, 1, 3, 8, 5, 4, 10, 9, 7]
Test 8: [2, 6, 8, 3, 11, 9, 7, 1, 12, 4, 10, 5]
Test 9: [5, 1, 6, 8, 3, 9, 4, 2, 10, 7]
Test 10: [11, 6, 9, 5, 7, 1, 4, 10, 2, 13, 3, 12, 8]
Test 11: [12, 2, 8, 13, 11, 4, 7, 10, 3, 1, 9, 5, 6, 14, 15]
Test 12: [6, 7, 9, 5, 8, 2, 4, 10, 1, 3]
Test 13: [4, 8, 1, 3, 2, 7, 6, 9, 10, 5, 11]
Test 14: [4, 10, 6, 3, 8, 9, 11, 1, 12, 13, 2, 5, 7]
Test 15: [15, 12, 7, 2, 1, 11, 14, 3, 13, 9, 10, 4, 5, 6, 8]

In [4]:
testing.make_tests("data/large", 10, 25, 30)

Test 1: [23, 24, 2, 17, 15, 5, 21, 16, 11, 19, 10, 4, 18, 22, 12, 25, 20, 7, 1, 14, 3, 9, 6, 13, 8]
Test 2: [6, 21, 9, 11, 15, 17, 19, 2, 13, 20, 16, 24, 14, 22, 18, 7, 25, 8, 4, 5, 3, 10, 12, 1, 23]
Test 3: [7, 20, 2, 14, 17, 18, 19, 9, 8, 3, 13, 22, 11, 6, 10, 23, 16, 1, 21, 26, 25, 12, 4, 5, 15, 24]
Test 4: [17, 22, 13, 6, 5, 7, 23, 2, 3, 18, 15, 24, 9, 8, 21, 1, 25, 20, 16, 11, 4, 14, 19, 10, 12]
Test 5: [28, 20, 23, 16, 5, 6, 9, 15, 4, 21, 26, 11, 22, 25, 18, 27, 1, 2, 14, 3, 13, 17, 19, 24, 7, 8, 10, 12]
Test 6: [14, 21, 27, 20, 23, 15, 8, 16, 9, 13, 5, 10, 7, 19, 4, 25, 18, 3, 22, 12, 1, 26, 6, 2, 24, 11, 17]
Test 7: [16, 2, 14, 23, 6, 17, 27, 4, 15, 13, 18, 9, 1, 11, 20, 26, 10, 22, 5, 24, 25, 12, 8, 3, 21, 7, 19]
Test 8: [6, 11, 26, 17, 19, 25, 14, 1, 23, 9, 13, 10, 22, 16, 20, 4, 24, 15, 8, 7, 3, 21, 12, 18, 5, 2]
Test 9: [4, 19, 9, 20, 6, 24, 26, 1, 25, 14, 8, 2, 21, 11, 18, 27, 16, 28, 15, 12, 10, 5, 22, 3, 13, 7, 23, 17]
Test 10: [25, 22, 1, 19, 26, 9, 3, 7, 10, 24, 16, 18, 2, 14, 20, 12, 11, 23, 5, 15, 21, 13, 4, 8, 17, 6]

In [2]:
testing.test_small_data("data/small")

Test case 1
Test case 2
Test case 3
Test case 4
Test case 5
Test case 6
Test case 7
Test case 8
Test case 9
Test case 10
Test case 11
Test case 12
Test case 13
Test case 14
Test case 15
Test case 16
Test case 17
Test case 18
Test case 19
Test case 20

,average_time,percent_of_optimal,percent_successfully_sorted
bruteforce,0.072057,100.0,100.0
branch_and_bound,0.000481,100.0,100.0
greedy,0.000117,85.0,100.0
vns,0.241404,100.0,100.0
genetic_algorithm,1.053595,100.0,100.0

In [ ]:
testing.test_medium_data("data/medium")

Test case 1
Test case 2
Test case 3
Test case 4
Test case 5
Test case 6
Test case 7
Test case 8
Test case 9
Test case 10
Test case 11
Test case 12
Test case 13
Test case 14
Test case 15

,average_time,percent_of_optimal,percent_successfully_sorted
branch_and_bound,3.954378,100.000000,100.0
greedy,0.000971,60.000000,100.0
vns,6.077249,60.000000,100.0
genetic_algorithm,7.871341,93.333333,100.0

In [3]:
testing.test_large_data("data/large")

Test case 1
Test case 2
Test case 3
Test case 4
Test case 5
Test case 6
Test case 7
Test case 8
Test case 9
Test case 10

,average_time,percent_best_result,percent_successfully_sorted
greedy,0.020734,90.0,100.0
vns,156.771521,0.0,100.0
genetic_algorithm,72.503255,10.0,100.0